-- ============================================================
-- MADEENAS STOCK — Migration 001: Core Schema
-- ============================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- USERS (extends auth.users)
-- ============================================================
CREATE TABLE public.users (
  id          UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   TEXT        NOT NULL,
  email       TEXT        NOT NULL UNIQUE,
  phone       TEXT,
  role        TEXT        NOT NULL DEFAULT 'VIEWER'
                          CHECK (role IN ('ADMIN','MANAGER','STORE_KEEPER','VIEWER')),
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_role ON public.users(role);
CREATE INDEX idx_users_email ON public.users(email);

-- ============================================================
-- LOCATIONS
-- ============================================================
CREATE TABLE public.locations (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT        NOT NULL,
  type        TEXT        NOT NULL CHECK (type IN ('WAREHOUSE','SHOP')),
  address     TEXT,
  phone       TEXT,
  manager_id  UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_locations_type ON public.locations(type);
CREATE INDEX idx_locations_active ON public.locations(is_active);

-- ============================================================
-- USER → LOCATION ASSIGNMENTS (for STORE_KEEPER scoping)
-- ============================================================
CREATE TABLE public.user_locations (
  user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  location_id UUID NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, location_id)
);

-- ============================================================
-- CATEGORIES (hierarchical, self-referencing)
-- ============================================================
CREATE TABLE public.categories (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT        NOT NULL UNIQUE,
  slug        TEXT        NOT NULL UNIQUE,
  prefix      TEXT        NOT NULL UNIQUE CHECK (char_length(prefix) BETWEEN 2 AND 5),
  description TEXT,
  image_url   TEXT,
  parent_id   UUID        REFERENCES public.categories(id) ON DELETE SET NULL,
  sort_order  INTEGER     NOT NULL DEFAULT 0,
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_categories_parent ON public.categories(parent_id);
CREATE INDEX idx_categories_slug ON public.categories(slug);
CREATE INDEX idx_categories_sort ON public.categories(sort_order);

-- ============================================================
-- PRODUCTS
-- ============================================================
CREATE TABLE public.products (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID        NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
  name        TEXT        NOT NULL,
  slug        TEXT        NOT NULL UNIQUE,
  description TEXT,
  image_urls  TEXT[]      NOT NULL DEFAULT '{}',
  is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
  created_by  UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_products_category ON public.products(category_id);
CREATE INDEX idx_products_slug ON public.products(slug);
CREATE INDEX idx_products_active ON public.products(is_active);

-- ============================================================
-- PRODUCT VARIANTS
-- ============================================================
CREATE TABLE public.product_variants (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id       UUID        NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  item_code        TEXT        UNIQUE,  -- auto-generated by trigger
  name             TEXT        NOT NULL,
  color            TEXT,
  color_hex        TEXT,
  width_inches     NUMERIC,
  gsm              INTEGER,
  material         TEXT,
  weave            TEXT,
  attributes       JSONB       NOT NULL DEFAULT '{}',
  unit             TEXT        NOT NULL CHECK (unit IN ('yards','meters','bales','pieces','rolls','kg')),
  pieces_per_bale  INTEGER,
  cost_price       NUMERIC     NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
  selling_price    NUMERIC     NOT NULL DEFAULT 0 CHECK (selling_price >= 0),
  barcode          TEXT        UNIQUE,
  min_stock_alert  NUMERIC     NOT NULL DEFAULT 0 CHECK (min_stock_alert >= 0),
  is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
  created_by       UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_variants_product    ON public.product_variants(product_id);
CREATE INDEX idx_variants_item_code  ON public.product_variants(item_code);
CREATE INDEX idx_variants_barcode    ON public.product_variants(barcode);
CREATE INDEX idx_variants_color      ON public.product_variants(color);
CREATE INDEX idx_variants_unit       ON public.product_variants(unit);
CREATE INDEX idx_variants_active     ON public.product_variants(is_active);

-- ============================================================
-- STOCK LEDGER (append-only, source of truth)
-- ============================================================
CREATE TABLE public.stock_ledger (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  variant_id     UUID        NOT NULL REFERENCES public.product_variants(id),
  location_id    UUID        NOT NULL REFERENCES public.locations(id),
  movement_type  TEXT        NOT NULL CHECK (movement_type IN (
    'STOCK_IN','STOCK_OUT','TRANSFER_OUT','TRANSFER_IN',
    'ADJUSTMENT_UP','ADJUSTMENT_DOWN','RETURN_IN','OPENING'
  )),
  quantity       NUMERIC     NOT NULL CHECK (quantity >= 0),
  unit           TEXT        NOT NULL,
  reference_type TEXT,       -- 'stock_in' | 'transfer' | 'adjustment'
  reference_id   UUID,
  notes          TEXT,
  created_by     UUID        REFERENCES public.users(id),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- NO updated_at — this table is IMMUTABLE after insert
);

CREATE INDEX idx_ledger_variant_loc ON public.stock_ledger(variant_id, location_id);
CREATE INDEX idx_ledger_location    ON public.stock_ledger(location_id);
CREATE INDEX idx_ledger_ref         ON public.stock_ledger(reference_id);
CREATE INDEX idx_ledger_type        ON public.stock_ledger(movement_type);
CREATE INDEX idx_ledger_date        ON public.stock_ledger(created_at DESC);

-- ============================================================
-- STOCK BALANCES (denormalised cache, trigger-maintained)
-- ============================================================
CREATE TABLE public.stock_balances (
  variant_id        UUID    NOT NULL REFERENCES public.product_variants(id),
  location_id       UUID    NOT NULL REFERENCES public.locations(id),
  quantity_on_hand  NUMERIC NOT NULL DEFAULT 0,
  quantity_reserved NUMERIC NOT NULL DEFAULT 0, -- pending TRANSFER_OUT (approved not yet dispatched)
  quantity_available NUMERIC GENERATED ALWAYS AS (quantity_on_hand - quantity_reserved) STORED,
  last_movement_at  TIMESTAMPTZ,
  PRIMARY KEY (variant_id, location_id)
);

CREATE INDEX idx_balances_location ON public.stock_balances(location_id);
CREATE INDEX idx_balances_variant  ON public.stock_balances(variant_id);

-- ============================================================
-- STOCK IN (Receiving)
-- ============================================================
CREATE TABLE public.stock_ins (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id    UUID        NOT NULL REFERENCES public.locations(id),
  supplier_name  TEXT        NOT NULL,
  reference_no   TEXT,
  received_date  DATE        NOT NULL,
  status         TEXT        NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','CONFIRMED')),
  notes          TEXT,
  confirmed_by   UUID        REFERENCES public.users(id),
  confirmed_at   TIMESTAMPTZ,
  created_by     UUID        REFERENCES public.users(id),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.stock_in_items (
  id           UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_in_id  UUID    NOT NULL REFERENCES public.stock_ins(id) ON DELETE CASCADE,
  variant_id   UUID    NOT NULL REFERENCES public.product_variants(id),
  quantity     NUMERIC NOT NULL CHECK (quantity > 0),
  unit         TEXT    NOT NULL,
  cost_price   NUMERIC NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
  notes        TEXT
);

CREATE INDEX idx_stock_ins_location ON public.stock_ins(location_id);
CREATE INDEX idx_stock_ins_status   ON public.stock_ins(status);
CREATE INDEX idx_stock_ins_date     ON public.stock_ins(received_date DESC);
CREATE INDEX idx_stock_in_items_si  ON public.stock_in_items(stock_in_id);

-- ============================================================
-- INTER-LOCATION TRANSFERS
-- ============================================================
CREATE TABLE public.transfers (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  from_location_id UUID        NOT NULL REFERENCES public.locations(id),
  to_location_id   UUID        NOT NULL REFERENCES public.locations(id),
  status           TEXT        NOT NULL DEFAULT 'DRAFT' CHECK (status IN (
    'DRAFT','PENDING_APPROVAL','APPROVED','IN_TRANSIT','RECEIVED','REJECTED','CANCELLED'
  )),
  approval_required BOOLEAN    NOT NULL DEFAULT FALSE,
  requested_by     UUID        REFERENCES public.users(id),
  requested_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_by      UUID        REFERENCES public.users(id),
  approved_at      TIMESTAMPTZ,
  approval_notes   TEXT,
  rejected_by      UUID        REFERENCES public.users(id),
  rejected_at      TIMESTAMPTZ,
  dispatched_by    UUID        REFERENCES public.users(id),
  dispatched_at    TIMESTAMPTZ,
  received_by      UUID        REFERENCES public.users(id),
  received_at      TIMESTAMPTZ,
  cancelled_by     UUID        REFERENCES public.users(id),
  cancelled_at     TIMESTAMPTZ,
  notes            TEXT,
  doc_url          TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_different_locations CHECK (from_location_id <> to_location_id)
);

CREATE TABLE public.transfer_items (
  id                  UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  transfer_id         UUID    NOT NULL REFERENCES public.transfers(id) ON DELETE CASCADE,
  variant_id          UUID    NOT NULL REFERENCES public.product_variants(id),
  quantity_requested  NUMERIC NOT NULL CHECK (quantity_requested > 0),
  quantity_dispatched NUMERIC CHECK (quantity_dispatched > 0),
  quantity_received   NUMERIC CHECK (quantity_received >= 0),
  unit                TEXT    NOT NULL,
  variance_notes      TEXT,
  UNIQUE (transfer_id, variant_id)
);

CREATE INDEX idx_transfers_from    ON public.transfers(from_location_id);
CREATE INDEX idx_transfers_to      ON public.transfers(to_location_id);
CREATE INDEX idx_transfers_status  ON public.transfers(status);
CREATE INDEX idx_transfers_date    ON public.transfers(requested_at DESC);
CREATE INDEX idx_transfer_items_tr ON public.transfer_items(transfer_id);

-- ============================================================
-- STOCK ADJUSTMENTS
-- ============================================================
CREATE TABLE public.stock_adjustments (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id  UUID        NOT NULL REFERENCES public.locations(id),
  reason       TEXT        NOT NULL CHECK (reason IN ('DAMAGE','LOSS','FOUND','RECOUNT','OTHER')),
  status       TEXT        NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','CONFIRMED')),
  notes        TEXT,
  confirmed_by UUID        REFERENCES public.users(id),
  confirmed_at TIMESTAMPTZ,
  created_by   UUID        REFERENCES public.users(id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.stock_adjustment_items (
  id            UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  adjustment_id UUID    NOT NULL REFERENCES public.stock_adjustments(id) ON DELETE CASCADE,
  variant_id    UUID    NOT NULL REFERENCES public.product_variants(id),
  unit          TEXT    NOT NULL,
  system_qty    NUMERIC NOT NULL CHECK (system_qty >= 0),
  physical_qty  NUMERIC NOT NULL CHECK (physical_qty >= 0),
  difference    NUMERIC GENERATED ALWAYS AS (physical_qty - system_qty) STORED,
  notes         TEXT
);

CREATE INDEX idx_adjustments_location ON public.stock_adjustments(location_id);
CREATE INDEX idx_adjustments_status   ON public.stock_adjustments(status);
CREATE INDEX idx_adj_items_adj        ON public.stock_adjustment_items(adjustment_id);

-- ============================================================
-- APP SETTINGS
-- ============================================================
CREATE TABLE public.settings (
  key         TEXT    PRIMARY KEY,
  value       JSONB   NOT NULL,
  description TEXT,
  updated_by  UUID    REFERENCES public.users(id),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- AUDIT LOG
-- ============================================================
CREATE TABLE public.audit_log (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name   TEXT        NOT NULL,
  record_id    UUID        NOT NULL,
  action       TEXT        NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
  old_data     JSONB,
  new_data     JSONB,
  performed_by UUID        REFERENCES public.users(id),
  performed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_table  ON public.audit_log(table_name, record_id);
CREATE INDEX idx_audit_user   ON public.audit_log(performed_by);
CREATE INDEX idx_audit_date   ON public.audit_log(performed_at DESC);
